### ISSUE TITLE
Меню выбора кнопок. Общий вид

### ISSUE THREAD

**Issue by oanaoooa** [opiruyan/BalanceBot#1]
Хочется чтобы кнопки с выбором не зависали в ленте, а располагались в меню ниже и могли использоваться единожды.

Фактический результат:
Кнопки сохраняются в ленте, кликабельны из любой точки алгоритма, нарушается последовательность.

![Screenshot 2024-03-05 at 3 05 49 PM](https://github.com/opiruyan/BalanceBot/assets/161847153/7944543f-af64-4258-b4d3-86a80fd845c0)

Ожидаемый результат:
Вынести кнопки выбора, как в примере 
![IMG_9655](https://github.com/opiruyan/BalanceBot/assets/161847153/b3d1a816-cfd8-4bf2-ae18-ce8fdcfaa40f)
![IMG_9656](https://github.com/opiruyan/BalanceBot/assets/161847153/9210e923-9a4d-401f-8479-66344af79dad)

**Comment by opiruyan** [comment]
@oanaoooa без проблем. 

Вопрос, что если проблема только в нарушении последовательности шагов алгоритма, то мы можем это пофиксить и не меняя вида кнопок.

**Comment by oanaoooa** [comment]
@opiruyan предлагаю вынести кнопки в панель клавиатуры, так намного удобнее использовать и приятнее выглядит.

плюс, создам отдельный тикет на удаление истории операций.

**Comment by opiruyan** [comment]
@oanaoooa чекай

**Comment by oanaoooa** [comment]
@opiruyan отлично, теперь немного косметики:

1) приводим к вертикальному положению порядка кнопок
2) убрать перенос строки в тексте кнопок (вторая панель)

Пример:
![IMG_9686](https://github.com/opiruyan/BalanceBot/assets/161847153/9561da71-f803-400b-964b-b3d415b57f86)

![IMG_9685](https://github.com/opiruyan/BalanceBot/assets/161847153/26973d9d-3b37-451f-aa7d-a098f030bcfe)

**Comment by opiruyan** [comment]
проверяй

**Comment by oanaoooa** [comment]
@opiruyan  проверено
