### ISSUE TITLE
[Функционал Панель кнопок] Справка

### ISSUE THREAD

**Issue by oanaoooa** [opiruyan/BalanceBot#4]
Кликаем на кнопку Справка
Открывается Панель кнопок и выходит Справочное сообщение.

Панель кнопок

Фактический результат: 
Кнопка Выход.

Ожидаемый результат:
В данном случае предлагаю сделать две кнопки Назад и Выход (вертикальное расположение соот-но) 
"Назад" - возврат к предыдущему шагу на панели кнопок, и возможность продолжить основной сценарий.

**Comment by opiruyan** [comment]
ты хочешь добавить справку ко всем шагам или оставть пока только на старте?

**Comment by oanaoooa** [comment]
пока только на старте

**Comment by opiruyan** [comment]
тогда уже можешь проверить

**Comment by oanaoooa** [comment]
проверено!
